{{- if and .Values.restate.enabled .Values.restate.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-restate-data
  labels:
    app.kubernetes.io/name: restate
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.restate.persistence.size }}
  {{- if .Values.restate.persistence.storageClass }}
  storageClassName: {{ .Values.restate.persistence.storageClass }}
  {{- end }}
{{- end }}
