apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-papers-mcp
  labels:
    app.kubernetes.io/name: papers-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 8012
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: papers-mcp
    app.kubernetes.io/instance: {{ .Release.Name }}
