apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-langfuse-web
  labels:
    app.kubernetes.io/name: langfuse-web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: langfuse-web
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-langfuse-worker
  labels:
    app.kubernetes.io/name: langfuse-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 3030
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: langfuse-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
